builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/memcache/main.go
    binary: memcache
    goos:
      - darwin
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
